---
- name: login Openshift
  shell: /usr/local/bin/oc login --insecure-skip-tls-verify  {{ openshift_console_url }} --username='{{ openshift_user }}' --password='{{ openshift_password }}'
 
- name: check login
  shell: /usr/local/bin/oc --kubeconfig ~/.kube/config whoami -t 
  register: login

- name: set schedule  false
  shell: /usr/local/bin/oc --kubeconfig ~/.kube/config adm manage-node {{ openshift_node }} --schedulable=false
  when: login.stderr != ""
  register: schedule

- name: check schedule false
  shell: /usr/local/bin/oc  --kubeconfig ~/.kube/config get node ocpmaster001 --output=jsonpath={.spec..unschedulable} 
  when: login.stderr != "" and schedule.stderr != ""  
  register: result

- name: msg result   
  debug:
    var: result.stdout
  when: result.stderr != ""
    # when: oclogincheck.stderr != ""