---
  
- name: (LOGIN) - Make login in Openshift cluster
  shell: /usr/local/bin/oc login --insecure-skip-tls-verify  {{ openshift_console_url }} --username='{{ openshift_user }}' --password='{{ openshift_password }}'
  register: login

- name: (CHECK) - Check schedule "current state before config"
  shell: /usr/local/bin/oc  --kubeconfig ~/.kube/config get node {{ openshift_node }} --output=jsonpath={.spec..unschedulable} 
  when: login.stderr == ""
  register: setschedulefalse

- name: (SET) - Set schedule=false
  shell: /usr/local/bin/oc --kubeconfig ~/.kube/config adm manage-node {{ openshift_node }} --schedulable=false
  when: setschedulefalse.stdout != "true" and setschedulefalse.stderr == ""
  register: schedule

- name: (MSG) - Output "Set schedule=false"
  debug:
    var: schedule   
  when: schedule is defined and setschedulefalse.stdout != "true" and setschedulefalse.stderr == ""

- name: (CHECK) - Check schedule state
  shell: /usr/local/bin/oc  --kubeconfig ~/.kube/config get node {{ openshift_node }}  --output=jsonpath={.spec..unschedulable} 
  when: setschedulefalse.stdout != "true" and setschedulefalse.stderr == ""
  register: result

- name: (MSG) - Result of Ansilble    
  debug: 
    var: result

